name: coffe_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  share_plus: ^10.1.2
  sqflite: ^2.4.1
  url_launcher: ^6.1.10  # Para abrir el correo en la pantalla de retroalimentación
  image_picker: ^0.8.7+3  # Para seleccionar imágenes de la galería o cámara

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.9.2  # Para generar el icono de la aplicación
  # flutter_native_splash: ^2.0.5  # Para configurar la pantalla de splash

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/splash.png
    - assets/espresso.jpg
    - assets/cappuccino.png
    - assets/mocha.png
    - assets/latte.jpg
    - assets/feedback_questions.json
    - assets/recipes.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"  # Ruta a tu imagen de icono

# flutter_native_splash:
#  color: "#ffffff"
#  image: assets/splash.png  
#  android: true
#  ios: true
